SELECT 
       [CustomerKey]
      --,[CustomerAlternateKey]
     -- ,[Title]
      ,[FirstName]
     -- ,[MiddleName]
      ,[LastName]
	  ,[FirstName] + ' ' + [LastName] AS [Full Name]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      ,[Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,[DateFirstPurchase]
      --,[CommuteDistance]
  FROM [AdventureWorksDW2022].[dbo].[DimCustomer]
  ORDER by
  CustomerKey ASC